### ISSUE TITLE
Support for meta attributes in markdown documents

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/markdown-sync#1]
One thing I'd like to be able to do with the WP-CLI command docs (https://github.com/wp-cli/wp-cli/issues/4244) is to have navigation links to the command's GitHub repo and "Create a new issue"

To do this, I'll need to be able to deliver some metadata in the markdown document that gets appropriately processed by WordPress.

Jekyll has some convention of using YAML at the top of the document:

![image](https://user-images.githubusercontent.com/36432/28619660-4548563a-71be-11e7-80f3-4e5c6893304d.png)

https://raw.githubusercontent.com/wp-cli/wp-cli.github.com/master/_posts/2011-11-06-version-0.3.md

What do you think about taking a similar approach?

**Comment by danielbachhuber** [comment]
Oh, on second thought, it'd be much easier to add a `meta` attribute to each manifest entry.

**Comment by rmccue** [comment]
I was actually thinking of exactly this, using the YAML frontmatter. I was thinking we could map it to REST API fields:

```yaml
---
template: whatever.php
meta:
    some_key: x
---
```

Potentially, we could use the manifest, but I'd rather move as much data out of the manifest as possible. If we do have it there, I'd probably use the YAML frontmatter to generate the data in the [manifest generation](https://github.com/WP-API/docs/blob/master/bin/generate-manifest.php) anyway.

**Comment by rmccue** [comment]
I also wonder whether this should be optional, for compatibility with migrating from Jekyll sites (which I'm planning on doing).

**Comment by roborourke** [comment]
Agree with YAML front matter as the better source for this metadata. #2 adds support for whitelisted meta keys and for some common Jekyll front matter items such as date, categories and tags.
